"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";

type Cat={id:string;name:string;group_name:string;sort_order:number};
type Img={id:string;category_id:string;title:string|null;image_url:string;storage_path:string|null;sort_order:number};
const SIZE=6;
export default function CatalogApp(){
 const [cats,setCats]=useState<Cat[]>([]),[imgs,setImgs]=useState<Img[]>([]);
 const [catId,setCatId]=useState(""),[openGroup,setOpenGroup]=useState("");
 const [admin,setAdmin]=useState(false),[login,setLogin]=useState(false),[adminMenu,setAdminMenu]=useState(false),[email,setEmail]=useState(""),[pass,setPass]=useState("");
 const [error,setError]=useState(""),[theme,setTheme]=useState<"dark"|"light">("dark"),[view,setView]=useState<"grid"|"list">("grid");
 const [q,setQ]=useState(""),[page,setPage]=useState(1),[modal,setModal]=useState<number|null>(null),[busy,setBusy]=useState(false);
 const checkAdmin=useCallback(async()=>{const {data:s}=await supabase.auth.getSession();const u=s.session?.user;if(!u){setAdmin(false);return}const {data}=await supabase.from("admin_users").select("user_id").eq("user_id",u.id).maybeSingle();setAdmin(!!data)},[]);
 const loadCats=useCallback(async()=>{const {data,error}=await supabase.from("categories").select("id,name,group_name,sort_order").eq("is_active",true).order("sort_order");if(error)throw error;const x=data||[];setCats(x);if(!catId||!x.some(c=>c.id===catId)){setCatId(x[0]?.id||"");setOpenGroup(x[0]?.group_name||"")}},[catId]);
 const loadImgs=useCallback(async()=>{if(!catId){setImgs([]);return}const {data,error}=await supabase.from("images").select("id,category_id,title,image_url,storage_path,sort_order").eq("category_id",catId).eq("is_active",true).order("sort_order").order("created_at",{ascending:false});if(error)throw error;setImgs(data||[])},[catId]);
 useEffect(()=>{setTheme((localStorage.getItem("temas-theme") as any)||"dark");setView((localStorage.getItem("temas-view") as any)||"grid");Promise.all([loadCats(),checkAdmin()]).catch(e=>alert(e.message));const {data:l}=supabase.auth.onAuthStateChange(()=>checkAdmin());return()=>l.subscription.unsubscribe()},[loadCats,checkAdmin]);
 useEffect(()=>{loadImgs().catch(e=>alert(e.message));setPage(1)},[loadImgs]);
 const groups=useMemo(()=>cats.reduce<Record<string,Cat[]>>((a,c)=>{(a[c.group_name||"Diğer"]??=[]).push(c);return a},{}),[cats]);
 const filtered=useMemo(()=>{const n=q.trim().toLocaleLowerCase("tr-TR");return !n?imgs:imgs.filter(i=>(i.title||"").toLocaleLowerCase("tr-TR").includes(n))},[imgs,q]);
 useEffect(()=>{if(modal===null)return;const h=(e:KeyboardEvent)=>{if(e.key==="Escape")setModal(null);if(e.key==="ArrowLeft")setModal(v=>v===null?null:(v-1+filtered.length)%filtered.length);if(e.key==="ArrowRight")setModal(v=>v===null?null:(v+1)%filtered.length)};document.body.style.overflow="hidden";document.addEventListener("keydown",h);return()=>{document.body.style.overflow="";document.removeEventListener("keydown",h)}},[modal,filtered.length]);
 const active=cats.find(c=>c.id===catId),pages=Math.max(1,Math.ceil(filtered.length/SIZE)),visible=filtered.slice((page-1)*SIZE,page*SIZE);
 async function doLogin(){setError("");setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password:pass});setBusy(false);if(error){setError(error.message);return}await checkAdmin();setLogin(false);setAdminMenu(false);setPass("")}
 async function doLogout(){await supabase.auth.signOut();setAdmin(false);setAdminMenu(false)}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){if(!admin||!catId)return;const fs=[...(e.target.files||[])];setBusy(true);try{const {data:u}=await supabase.auth.getUser();for(const f of fs){const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${catId}/${crypto.randomUUID()}-${safe}`;let r=await supabase.storage.from("katalog").upload(path,f,{cacheControl:"3600"});if(r.error)throw r.error;const pub=supabase.storage.from("katalog").getPublicUrl(path).data.publicUrl;const ins=await supabase.from("images").insert({category_id:catId,title:f.name.replace(/\.[^/.]+$/,""),image_url:pub,storage_path:path,file_size:f.size,mime_type:f.type,uploaded_by:u.user?.id||null});if(ins.error)throw ins.error}await loadImgs()}catch(x){alert(x instanceof Error?x.message:"Yükleme başarısız")}finally{setBusy(false);e.target.value=""}}
 async function del(i:Img){if(!admin||!confirm("Bu görsel silinsin mi?"))return;if(i.storage_path){const r=await supabase.storage.from("katalog").remove([i.storage_path]);if(r.error)return alert(r.error.message)}const d=await supabase.from("images").delete().eq("id",i.id);if(d.error)alert(d.error.message);else loadImgs()}
 async function addCat(){if(!admin)return;const name=prompt("Kategori adı:");if(!name?.trim())return;const group=prompt("Grup adı:","Özel Günler")||"Diğer";const r=await supabase.from("categories").insert({name:name.trim(),group_name:group,sort_order:cats.length*10+10});if(r.error)alert(r.error.message);else loadCats()}
 async function delCat(c:Cat){if(!admin||!confirm(`“${c.name}” kategorisi kaldırılsın mı?\n\nKategori gizlenecek; bağlı görseller Supabase'den silinmeyecek.`))return;setBusy(true);try{const r=await supabase.from("categories").update({is_active:false}).eq("id",c.id);if(r.error)throw r.error;await loadCats()}catch(x){alert(x instanceof Error?x.message:"Kategori kaldırılamadı")}finally{setBusy(false)}}
 function download(i:Img){const a=document.createElement("a");a.href=i.image_url;a.download=i.title||"kartpostal";a.target="_blank";document.body.appendChild(a);a.click();a.remove()}
 return <main className={`app ${theme}`}>
  <aside><div className="brand"><img src="/temas-logo.png"/><span>KATALOĞU</span></div><div className="side-title-row"><small>KATEGORİLER</small>{admin&&<div className="mini-action"><span className="mini-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3.5 6.5h6l2 2h9v10a2 2 0 0 1-2 2h-15a2 2 0 0 1-2-2v-10a2 2 0 0 1 2-2Z"/></svg></span><button className="mini-plus" onClick={addCat} aria-label="Kategori ekle" title="Kategori ekle">＋</button></div>}</div>{Object.entries(groups).map(([g,list])=><section className={`group ${openGroup===g?"open":""}`} key={g}><button onClick={()=>setOpenGroup(openGroup===g?"":g)}><span>{g}</span><span>⌄</span></button><div>{list.map(c=><div className={`cat-row ${catId===c.id?"active":""}`} key={c.id}><button className="cat-select" onClick={()=>setCatId(c.id)}>{c.name}</button>{admin&&<button className="cat-delete" onClick={()=>delCat(c)} aria-label={`${c.name} kategorisini kaldır`} title="Kategoriyi kaldır">×</button>}</div>)}</div></section>)}</aside>
  <section className="content"><header><div><h1>{active?.name||"Temaş Kataloğu"}</h1><p>Toplam <b>{filtered.length}</b> görsel</p></div><div className="tools"><div className="admin-lock-wrap"><button className={`icon-btn lock-btn ${admin?"unlocked":"locked"}`} aria-label={admin?"Admin menüsünü aç":"Admin girişi"} title={admin?"Admin modu":"Admin girişi"} onClick={()=>{if(admin)setAdminMenu(v=>!v);else setLogin(true)}}>{admin?<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 10V7a5 5 0 0 1 9.6-2M6 10h12a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2Zm6 4v3"/></svg>:<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 10V7a5 5 0 0 1 10 0v3M6 10h12a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2Zm6 4v3"/></svg>}</button>{admin&&adminMenu&&<div className="admin-popover"><button onClick={doLogout}>Çıkış Yap</button></div>}</div><button className="icon-btn" onClick={()=>{const n=theme==="dark"?"light":"dark";setTheme(n);localStorage.setItem("temas-theme",n)}}>{theme==="dark"?"☀":"☾"}</button><label>⌕<input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Ara..."/></label><div className="switch"><button className={view==="grid"?"active":""} onClick={()=>{setView("grid");localStorage.setItem("temas-view","grid")}}>▦</button><button className={view==="list"?"active":""} onClick={()=>{setView("list");localStorage.setItem("temas-view","list")}}>☰</button></div>{admin&&<div className="add-image-control"><span className="image-symbol" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m4 17 4.5-4 3.5 3 2.5-2 5.5 5"/></svg></span><label className="image-plus" aria-label="Görsel ekle" title="Görsel ekle">＋<input type="file" accept="image/*" multiple onChange={upload}/></label></div>}</div></header>{busy&&<p className="busy">İşlem sürüyor…</p>}
  <div className={`gallery ${view}`}>{visible.map((i,idx)=><article key={i.id}><button className="pic" onClick={()=>setModal((page-1)*SIZE+idx)}><img src={i.image_url}/></button><footer><span>{i.title||"İsimsiz görsel"}</span><div>{admin&&<button onClick={()=>download(i)}>⇩</button>}<button onClick={()=>setModal((page-1)*SIZE+idx)}>◉</button>{admin&&<button onClick={()=>del(i)}>×</button>}</div></footer></article>)}</div>{!visible.length&&<div className="empty">Bu kategoride henüz görsel yok.</div>}<nav><button disabled={page===1} onClick={()=>setPage(page-1)}>‹</button>{Array.from({length:pages},(_,i)=>i+1).map(n=><button className={page===n?"active":""} onClick={()=>setPage(n)} key={n}>{n}</button>)}<button disabled={page===pages} onClick={()=>setPage(page+1)}>›</button></nav></section>
  {modal!==null&&filtered[modal]&&<div className="modal" onClick={e=>{if(e.target===e.currentTarget)setModal(null)}}><button className="close" onClick={()=>setModal(null)}>×</button><button className="prev" onClick={()=>setModal((modal-1+filtered.length)%filtered.length)}>‹</button><img src={filtered[modal].image_url}/><button className="next" onClick={()=>setModal((modal+1)%filtered.length)}>›</button>{admin&&<button className="mdown" onClick={()=>download(filtered[modal])}>Görseli indir</button>}</div>}
  {login&&<div className="backdrop" onClick={e=>{if(e.target===e.currentTarget)setLogin(false)}}><div className="dialog"><h2>Admin Girişi</h2><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-posta"/><input value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")doLogin()}} type="password" placeholder="Şifre"/>{error&&<p className="err">{error}</p>}<div><button onClick={()=>setLogin(false)}>İptal</button><button className="primary" disabled={busy} onClick={doLogin}>Giriş Yap</button></div></div></div>}
 </main>
}
